Repository The-Powder-Toy/The-Powder-Toy, pull requests merged in 2020-10, with the labels that each got.

#730 Make Copy and Cut buttons disappear when no text is selected
  src/gui/interface/Textbox.cpp
Labels: Enhancement

#707 Add VSNS
  src/simulation/ElementNumbers.h
  src/simulation/elements/VSNS.cpp
Labels: New element

#724 Add element ROCK.
  src/simulation/ElementNumbers.h
  src/simulation/Simulation.cpp
  src/simulation/elements/FIRE.cpp
  src/simulation/elements/ROCK.cpp
  src/simulation/elements/WATR.cpp
Labels: New element

#731 Custom GOL
  src/client/GameSave.cpp
  src/gui/game/GOLTool.cpp
  src/gui/game/GameController.cpp
  src/gui/game/GameController.h
  src/gui/game/GameModel.cpp
  src/gui/game/GameModel.h
  src/gui/game/GameView.cpp
  src/gui/game/PropertyTool.cpp
  src/gui/game/SampleTool.cpp
  src/gui/game/Tool.h
  src/simulation/BuiltinGOL.h
  src/simulation/Element.cpp
  src/simulation/GOLMenu.h
  src/simulation/GOLString.cpp
  src/simulation/GOLString.h
  src/simulation/Simulation.cpp
  src/simulation/Simulation.h
  src/simulation/SimulationData.cpp
  src/simulation/SimulationData.h
  src/simulation/elements/BCLN.cpp
  src/simulation/elements/CLNE.cpp
  src/simulation/elements/CONV.cpp
  src/simulation/elements/LIFE.cpp
  src/simulation/elements/PBCN.cpp
  src/simulation/elements/PCLN.cpp
Labels: New feature

#693 limit redrawing frequency (optimization)
  src/PowderToySDL.cpp
  src/gui/interface/Engine.cpp
  src/gui/interface/Engine.h
  src/gui/options/OptionsController.cpp
  src/gui/options/OptionsController.h
  src/gui/options/OptionsModel.cpp
  src/gui/options/OptionsModel.h
  src/gui/options/OptionsView.cpp
  src/gui/options/OptionsView.h
  src/lua/LegacyLuaAPI.cpp
  src/lua/LuaScriptHelper.h
  src/lua/LuaScriptInterface.cpp
Labels: New feature

#739 Fixing the fonttool.py with PEP8, ArgParse, Unused Imports, Unresolved References (Code Cleanup for fonttool.py)
  fonttool.py
Labels: Enhancement
